package GUI;

import GUI.Stats.UsersStatPanel;
import GUI.Welcome.WelcomePanel;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class Start {
    private JPanel containerPanel;
    private JPanel cardsContainer;
    private JButton backBtn;
    private WelcomePanel welcomeCard;
    private UsersStatPanel statCard;
    private CardLayout cl;

    private CardName currentCardName = null;
    private CardName prevCardName = null;

    public Start(Frame frame) {
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Start");

        Start start = new Start(frame);
        start.createUIComponents();

        frame.setContentPane(start.containerPanel);
        setFrameIcon(frame);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private static void setFrameIcon(JFrame frame) {
        ImageIcon img = new ImageIcon("C:\\Users\\rluva\\Programming\\FrontEnd\\Desktop\\Java\\Maze\\src\\main\\resources\\icons\\maze-game-icon-white.png");
        frame.setIconImage(img.getImage());
    }

    private void createUIComponents() {
        createAndAttachWelcomeCard();
        createAndAttachStatsCard();

        cl = (CardLayout) (this.cardsContainer.getLayout());

        showCard(CardName.WELCOME);

        backBtn.addActionListener(e -> {
            this.cl.previous(this.cardsContainer);

            currentCardName = prevCardName;
            prevCardName = null;

            if (currentCardName == CardName.WELCOME) {
                backBtn.setVisible(false);
            }
        });
    }

    private void createAndAttachWelcomeCard() {
        welcomeCard = new WelcomePanel(this::generatedClicked, this::playClicked, this::statsClicked);
        welcomeCard.init();

        addCard(welcomeCard, CardName.WELCOME);
        welcomeCard.initComponents();
    }

    private void generatedClicked() {
        System.out.println("Not Supported Yet");
        showCard(CardName.GENERATOR);
    }

    private void playClicked() {
        System.out.println("Not Supported Yet");
        showCard(CardName.PLAY);
    }

    private void statsClicked() {
        showCard(CardName.STATS);
    }

    private void createAndAttachStatsCard() {
        if (statCard == null) {
            statCard = new UsersStatPanel();
        }

        statCard.init();

        addCard(statCard, CardName.STATS);
        statCard.initComponents();
    }

    private void showCard(CardName cardName) {
        prevCardName = currentCardName;
        currentCardName = cardName;

        cl.show(this.cardsContainer, cardName.getValue());

        this.backBtn.setVisible(currentCardName != CardName.WELCOME);
    }

    private void addCard(JPanel panel, CardName cardName) {
        cardsContainer.add(panel, cardName.getValue());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        containerPanel = new JPanel();
        containerPanel.setLayout(new FormLayout("fill:529px:noGrow", "center:9px:noGrow,top:4dlu:noGrow,center:196px:noGrow"));
        containerPanel.setMaximumSize(new Dimension(530, 133));
        containerPanel.setMinimumSize(new Dimension(530, 133));
        containerPanel.setPreferredSize(new Dimension(530, 133));
        backBtn = new JButton();
        backBtn.setText("Back");
        backBtn.setVisible(false);
        CellConstraints cc = new CellConstraints();
        containerPanel.add(backBtn, cc.xywh(1, 1, 1, 2, CellConstraints.LEFT, CellConstraints.DEFAULT));
        cardsContainer = new JPanel();
        cardsContainer.setLayout(new CardLayout(0, 0));
        containerPanel.add(cardsContainer, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return containerPanel;
    }

}
