package GUI;

import GUI.Stats.UsersStatPanel;
import GUI.Welcome.WelcomePanel;

import javax.swing.*;
import java.awt.*;

public class Start {
    private JPanel containerPanel;
    private WelcomePanel welcomeCard;
    private UsersStatPanel statCard;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Start");

        Start start = new Start();
        start.createUIComponents();

        frame.setContentPane(start.containerPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        createAndAttachWelcomeCard();
    }

    private void createAndAttachWelcomeCard() {
        welcomeCard = new WelcomePanel();
        welcomeCard.init();

        containerPanel.add(welcomeCard, "Card1");
        welcomeCard.initComponents();
    }

    private void createAndAttachStatsCard() {
        statCard = new UsersStatPanel();
        statCard.init();

        containerPanel.add(statCard, "Card2");
        statCard.initComponents();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        containerPanel = new JPanel();
        containerPanel.setLayout(new CardLayout(0, 0));
        containerPanel.setMaximumSize(new Dimension(313, 133));
        containerPanel.setMinimumSize(new Dimension(313, 133));
        containerPanel.setPreferredSize(new Dimension(313, 133));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return containerPanel;
    }

}
