package GUI;

import GUI.Stats.UsersStatPanel;
import GUI.Welcome.WelcomePanel;

import javax.swing.*;
import java.awt.*;

public class Start {
    private JPanel containerPanel;
    private WelcomePanel welcomeCard;
    private UsersStatPanel statCard;
    private CardLayout cl;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Start");

        Start start = new Start();
        start.createUIComponents();

        frame.setContentPane(start.containerPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        createAndAttachWelcomeCard();
        createAndAttachStatsCard();

        cl = (CardLayout) (this.containerPanel.getLayout());

        showCard(CardName.WELCOME);

    }

    private void createAndAttachWelcomeCard() {
        welcomeCard = new WelcomePanel(this::generatedClicked, this::playClicked, this::statsClicked);
        welcomeCard.init();

        containerPanel.add(welcomeCard, CardName.WELCOME.getValue());
        welcomeCard.initComponents();
    }


    private void generatedClicked() {
        System.out.println("Not Supported Yet");
        showCard(CardName.GENERATOR);
    }

    private void playClicked() {
        System.out.println("Not Supported Yet");
        showCard(CardName.PLAY);
    }

    private void statsClicked() {
        showCard(CardName.STATS);
    }

    private void showCard(CardName cardName) {
        cl.show(this.containerPanel, cardName.getValue());
    }

    private void createAndAttachStatsCard() {
        if (statCard == null) {
            statCard = new UsersStatPanel();
        }

        statCard.init();

        containerPanel.add(statCard, CardName.STATS.getValue());
        statCard.initComponents();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        containerPanel = new JPanel();
        containerPanel.setLayout(new CardLayout(0, 0));
        containerPanel.setMaximumSize(new Dimension(313, 133));
        containerPanel.setMinimumSize(new Dimension(313, 133));
        containerPanel.setPreferredSize(new Dimension(313, 133));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return containerPanel;
    }

}
