package GUI.Welcome;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class Start {
    private JPanel containerPanel;
    private JPanel welcomeCard;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Start");

        Start start = new Start();
        start.createUIComponents();

        frame.setContentPane(start.containerPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        createAndAttachWelcomeCard();
    }

    private void createAndAttachWelcomeCard() {
        welcomeCard = new WelcomePanel();
        ((WelcomePanel) welcomeCard).init();

        containerPanel.add(welcomeCard, "Card1");
        ((WelcomePanel) welcomeCard).initComponents();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        containerPanel = new JPanel();
        containerPanel.setLayout(new CardLayout(0, 0));
        containerPanel.setMaximumSize(new Dimension(313, 133));
        containerPanel.setMinimumSize(new Dimension(313, 133));
        containerPanel.setPreferredSize(new Dimension(313, 133));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return containerPanel;
    }

}
