package GUI.Stats;

import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

public class Stats {
    private JPanel container;
    private JPanel statPanel;
    private JLabel header;
    private JComboBox comboBox1;
    private JLabel userSelectionLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
    }
}
