package GUI.Stats;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class Stats {
    private JPanel container;
    private JPanel statPanel;
    private JLabel header;
    private JComboBox userSelection;
    private JLabel userSelectionLabel;
    private JPanel singleUserStats;
    private JLabel totalGameValueLabel;
    private JLabel totalTimeLimitedGamesValueLabel;
    private JLabel maxMazeArePlayedValueLabel;
    private JLabel totalUsersPlayedValueLabel;
    private JLabel totalTimePlayedValueLabel;
    private JLabel timePlayedValueLabel;
    private JLabel winningPercentageValueLabel;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Stats");
        frame.setContentPane(new Stats().container);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        container = new JPanel();
        container.setLayout(new CardLayout(0, 0));
        statPanel = new JPanel();
        statPanel.setLayout(new FormLayout("fill:43px:noGrow,left:4dlu:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:42px:noGrow,left:4dlu:noGrow,fill:109px:noGrow,left:4dlu:noGrow,fill:65px:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:8dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:106px:noGrow"));
        container.add(statPanel, "Card1");
        header = new JLabel();
        Font headerFont = this.$$$getFont$$$("Source Code Pro", Font.BOLD, 18, header.getFont());
        if (headerFont != null) {
            header.setFont(headerFont);
        }
        header.setHorizontalAlignment(0);
        header.setText("Stats");
        CellConstraints cc = new CellConstraints();
        statPanel.add(header, cc.xyw(1, 1, 10));
        singleUserStats = new JPanel();
        singleUserStats.setLayout(new FormLayout("fill:63px:noGrow,left:4dlu:noGrow,fill:84px:noGrow,left:4dlu:noGrow,fill:158px:noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        statPanel.add(singleUserStats, cc.xywh(1, 7, 10, 3));
        totalGameValueLabel = new JLabel();
        totalGameValueLabel.setText("0");
        singleUserStats.add(totalGameValueLabel, cc.xy(5, 1, CellConstraints.LEFT, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, -1, label1.getFont());
        if (label1Font != null) {
            label1.setFont(label1Font);
        }
        label1.setText("Total Games");
        singleUserStats.add(label1, new CellConstraints(1, 1, 3, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        totalTimeLimitedGamesValueLabel = new JLabel();
        totalTimeLimitedGamesValueLabel.setText("0");
        singleUserStats.add(totalTimeLimitedGamesValueLabel, cc.xy(5, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
        if (label2Font != null) {
            label2.setFont(label2Font);
        }
        label2.setText("Total Time Limited Games");
        singleUserStats.add(label2, new CellConstraints(1, 3, 4, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        maxMazeArePlayedValueLabel = new JLabel();
        maxMazeArePlayedValueLabel.setText("0");
        singleUserStats.add(maxMazeArePlayedValueLabel, cc.xy(5, 5, CellConstraints.LEFT, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, -1, label3.getFont());
        if (label3Font != null) {
            label3.setFont(label3Font);
        }
        label3.setText("Max Maze Area Played");
        singleUserStats.add(label3, new CellConstraints(1, 5, 4, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        timePlayedValueLabel = new JLabel();
        timePlayedValueLabel.setText("0s");
        singleUserStats.add(timePlayedValueLabel, cc.xy(5, 7, CellConstraints.LEFT, CellConstraints.DEFAULT));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, -1, label4.getFont());
        if (label4Font != null) {
            label4.setFont(label4Font);
        }
        label4.setText("Time Played");
        singleUserStats.add(label4, new CellConstraints(1, 7, 4, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        winningPercentageValueLabel = new JLabel();
        winningPercentageValueLabel.setText("0");
        singleUserStats.add(winningPercentageValueLabel, cc.xy(5, 9, CellConstraints.LEFT, CellConstraints.DEFAULT));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.BOLD, -1, label5.getFont());
        if (label5Font != null) {
            label5.setFont(label5Font);
        }
        label5.setText("Winning Percentage");
        singleUserStats.add(label5, new CellConstraints(1, 9, 4, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        totalUsersPlayedValueLabel = new JLabel();
        totalUsersPlayedValueLabel.setText("0");
        statPanel.add(totalUsersPlayedValueLabel, cc.xy(6, 3));
        final JLabel label6 = new JLabel();
        label6.setText("Total Users Played");
        statPanel.add(label6, cc.xy(4, 3));
        final JLabel label7 = new JLabel();
        label7.setText("Total Time Played");
        statPanel.add(label7, cc.xy(8, 3));
        totalTimePlayedValueLabel = new JLabel();
        totalTimePlayedValueLabel.setText("0s");
        statPanel.add(totalTimePlayedValueLabel, cc.xy(10, 3));
        userSelection = new JComboBox();
        userSelection.setMinimumSize(new Dimension(150, 24));
        userSelection.setPreferredSize(new Dimension(150, 24));
        statPanel.add(userSelection, cc.xyw(6, 5, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        userSelectionLabel = new JLabel();
        userSelectionLabel.setText("User");
        statPanel.add(userSelectionLabel, new CellConstraints(4, 5, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 10, 0, 0)));
        userSelectionLabel.setLabelFor(userSelection);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) {
            return null;
        }
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return container;
    }

}
